import "@styles/globals.scss";
import { monserrat } from "@/config/ui/font.ui";
import styles from "@styles/layouts/principal-layout.module.scss";
import logo from "@/assets/images/instaleap-logo.webp";
import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${monserrat.className}`}>
        <div className={styles.layout}>
          <div className={styles.sideMenu}>
            <Image src={logo} className={styles.logo} alt="Instaleap" />
          </div>
          <main className={styles.content}>{children}</main>
        </div>
      </body>
    </html>
  );
}
