import "@/config/styles/globals.scss";
import { monserrat } from "@/config/ui/font.ui";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${monserrat.className}`}>{children}</body>
    </html>
  );
}
